package com.pdv.project.model;
// Generated 29 nov. 2017 14:58:04 by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;

/**
 * Adresse generated by hbm2java
 */
@Entity
@Table(name = "adresse", schema = "pdv")
@Data
@Builder
@AllArgsConstructor
public class Adresse {

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Integer id;

	@Column(name = "adresse_libre", length = 100)
	private String adresselibre;

	@Column(name = "codepostal", length = 10)
	private String codepostal;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "villefk_adresse", nullable = false)
	private Ville ville;

	public Adresse() {
		super();
	}

}
