package com.pdv.project.model;
// Generated 29 nov. 2017 15:21:13 by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Carburant generated by hbm2java
 */
@Entity
@Table(name = "carburant", schema = "pdv", uniqueConstraints = @UniqueConstraint(columnNames = "prixfk_carburant"))
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class Carburant implements java.io.Serializable {

	private static final long serialVersionUID = 4758548934584824324L;

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Integer id;

	@Column(name = "code", length = 10)
	private String code;

	@Column(name = "nom", length = 20)
	private String nom;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "prixfk_carburant", nullable = false)
	private Prix prix;
}
