package com.pdv.project.model;
// Generated 29 nov. 2017 15:40:03 by Hibernate Tools 5.2.6.Final

import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;

/**
 * Fermeture generated by hbm2java
 */
@Entity
@Table(name = "fermeture", schema = "pdv")
@Data
@Builder
@AllArgsConstructor
public class Fermeture {

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Integer id;

	@Temporal(TemporalType.DATE)
	@Column(name = "debut", nullable = false, length = 13)
	private Date debut;

	@Temporal(TemporalType.DATE)
	@Column(name = "fin", nullable = true, length = 13)
	private Date fin;

	@JoinColumn(name = "type", unique = true, nullable = false)
	private String type;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fermeture")
	private Set<PointDeVente> pointDeVentes;

}
