package com.pdv.project.model;
// Generated 29 nov. 2017 15:40:03 by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * PdvServiceId generated by hbm2java
 */
@Embeddable
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class PdvServiceId implements java.io.Serializable {

	private static final long serialVersionUID = -8022107771807495451L;
	
	@Column(name = "id", nullable = false)
	private int id;
	
	@Column(name = "pdvservicefk_service", nullable = false)
	private int pdvservicefkService;
	
	@Column(name = "pdvservicefk_pdv", nullable = false)
	private int pdvservicefkPdv;

}
