package com.pdv.project.model;
// Generated 29 nov. 2017 15:40:03 by Hibernate Tools 5.2.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PdvService generated by hbm2java
 */
@Entity
@Table(name = "pdv_service", schema = "pdv")
//@Data
public class PdvService implements java.io.Serializable {

	private static final long serialVersionUID = -7952702656188507757L;
	
	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "pdvservicefkService", column = @Column(name = "pdvservicefk_service", nullable = false)),
			@AttributeOverride(name = "pdvservicefkPdv", column = @Column(name = "pdvservicefk_pdv", nullable = false)) })
	private PdvServiceId id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pdvservicefk_pdv", nullable = false, insertable = false, updatable = false)
	private PointDeVente pointDeVente;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pdvservicefk_service", nullable = false, insertable = false, updatable = false)
	private Service service;
	
	public PdvService() {
		super();
	}

	public PdvService(PointDeVente pointDeVente, Service service) {
		super();
		this.pointDeVente = pointDeVente;
		this.service = service;
	}

	public PdvServiceId getId() {
		return id;
	}

	public void setId(PdvServiceId id) {
		this.id = id;
	}

	public PointDeVente getPointDeVente() {
		return pointDeVente;
	}

	public void setPointDeVente(PointDeVente pointDeVente) {
		this.pointDeVente = pointDeVente;
	}

	public Service getService() {
		return service;
	}

	public void setService(Service service) {
		this.service = service;
	}
	
}
