package com.pdv.project.model;
// Generated 29 nov. 2017 15:40:03 by Hibernate Tools 5.2.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * PdvService generated by hbm2java
 */
@Entity
@Table(name = "pdv_service", schema = "pdv")
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class PdvService implements java.io.Serializable {

	private static final long serialVersionUID = -7952702656188507757L;
	
	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "pdvservicefkService", column = @Column(name = "pdvservicefk_service", nullable = false)),
			@AttributeOverride(name = "pdvservicefkPdv", column = @Column(name = "pdvservicefk_pdv", nullable = false)) })
	private PdvServiceId id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pdvservicefk_pdv", nullable = false, insertable = false, updatable = false)
	private PointDeVente pointDeVente;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pdvservicefk_service", nullable = false, insertable = false, updatable = false)
	private Service service;
	
}
