package com.pdv.project.model;
// Generated 29 nov. 2017 15:40:03 by Hibernate Tools 5.2.6.Final

import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Prix generated by hbm2java
 */
@Entity
@Table(name = "prix", schema = "pdv")
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class Prix implements java.io.Serializable {

	private static final long serialVersionUID = 8005273256896051826L;

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.AUTO)
	private int id;

	@Column(name = "identifiant", nullable = false)
	private Integer identifiant;

	@Column(name = "nom", length = 20)
	private String nom;

	@Temporal(TemporalType.DATE)
	@Column(name = "maj", nullable = false, length = 13)
	private Date maj;

	@Column(name = "valeur", precision = 17, scale = 17)
	private Double valeur;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pointdeventefk_prix", nullable = false)
	private PointDeVente pointDeVente;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prix")
	private Set<Carburant> carburants;
}
