package com.pdv.project.model;
// Generated 29 nov. 2017 15:40:03 by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * VillesFrance generated by hbm2java
 */
@Entity
@Table(name = "villes_france", schema = "commun")
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class Ville {

	@Id
	@Column(name = "ville_id", unique = true, nullable = false)
	private int villeId;

	@Column(name = "ville_departement", length = 3)
	private String villeDepartement;

	@Column(name = "ville_slug")
	private String villeSlug;

	@Column(name = "ville_nom", length = 45)
	private String villeNom;

	@Column(name = "ville_nom_simple", length = 45)
	private String villeNomSimple;

	@Column(name = "ville_nom_reel", length = 45)
	private String villeNomReel;

	@Column(name = "ville_nom_soundex", length = 20)
	private String villeNomSoundex;

	@Column(name = "ville_nom_metaphone", length = 22)
	private String villeNomMetaphone;

	@Column(name = "ville_code_postal")
	private String villeCodePostal;

	@Column(name = "ville_commune", length = 3)
	private String villeCommune;

	@Column(name = "ville_code_commune", nullable = false, length = 5)
	private String villeCodeCommune;

	@Column(name = "ville_arrondissement")
	private Short villeArrondissement;

	@Column(name = "ville_canton", length = 4)
	private String villeCanton;

	@Column(name = "ville_amdi")
	private Short villeAmdi;

	@Column(name = "ville_population_2010")
	private Long villePopulation2010;

	@Column(name = "ville_population_1999")
	private Long villePopulation1999;

	@Column(name = "ville_population_2012")
	private Long villePopulation2012;

	@Column(name = "ville_densite_2010")
	private Integer villeDensite2010;

	@Column(name = "ville_surface", precision = 17, scale = 17)
	private Double villeSurface;

	@Column(name = "ville_longitude_deg", precision = 17, scale = 17)
	private Double villeLongitudeDeg;

	@Column(name = "ville_latitude_deg", precision = 17, scale = 17)
	private Double villeLatitudeDeg;

	@Column(name = "ville_longitude_grd", length = 9)
	private String villeLongitudeGrd;

	@Column(name = "ville_latitude_grd", length = 8)
	private String villeLatitudeGrd;

	@Column(name = "ville_longitude_dms", length = 9)
	private String villeLongitudeDms;

	@Column(name = "ville_latitude_dms", length = 8)
	private String villeLatitudeDms;

	@Column(name = "ville_zmin")
	private Long villeZmin;

	@Column(name = "ville_zmax")
	private Long villeZmax;
	

}
